/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government.ComplaintManager;

import Business.Enterprises.Enterprise;
import Business.Enterprises.Government;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.UserAccount;
import Business.WorkRequest.SuspectDrugWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Mayank
 */
public class ViewSuspectDrugComplaintJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    Government selectedEnterprise;
    Network selectedNetwork;
    SuspectDrugWorkRequest request;


    /**
     * Creates new form CreateDrugJPanel
     */
    public ViewSuspectDrugComplaintJPanel(JPanel userProcessContainer, Enterprise selectedEnterprise, UserAccount userAccount, Network selectedNetwork, SuspectDrugWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.selectedEnterprise = (Government)selectedEnterprise;
        this.selectedNetwork = selectedNetwork;
        this.request = request;
        
        enterpriseNameJLabel.setText(" --  " + selectedEnterprise.getEnterpriseName());
        networkNameJLabel.setText(selectedNetwork.getNetworkName());
        
        Organization o = selectedEnterprise.getMyOrganization(userAccount);
        organizationNameJLabel.setText(o.getOrganizationName());
        
        uniqueIDJTextField.setText(String.valueOf(request.getSuspectDrug().getMedicinePackage().getUniqueID()));
        drugNameJTextField.setText(request.getSuspectDrug().getMedicinePackage().getBatch().getDrug().getDrugName());
        manufacturerNameJTextField.setText(request.getSuspectDrug().getMedicinePackage().getBatch().getDrug().getManufacturerName());
        manufacturingDateJTextField.setText(request.getSuspectDrug().getMedicinePackage().getBatch().getManufacturingDate());
        expiryDateJTextField.setText(request.getSuspectDrug().getMedicinePackage().getBatch().getExpiryDate());
        batchNumberJTextField.setText(String.valueOf(request.getSuspectDrug().getMedicinePackage().getBatch().getBatchID()));
        adverseEventJTextField.setText(request.getSuspectDrug().getAdverseEvent());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        organizationNameJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        titleJLabel = new javax.swing.JLabel();
        manufacturerNameJLabel = new javax.swing.JLabel();
        drugNameJLabel = new javax.swing.JLabel();
        statusJLabel = new javax.swing.JLabel();
        uniqueIDJTextField = new javax.swing.JTextField();
        drugNameJTextField = new javax.swing.JTextField();
        manufacturerNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        manufacturerNameJLabel1 = new javax.swing.JLabel();
        manufacturerNameJLabel3 = new javax.swing.JLabel();
        manufacturingDateJTextField = new javax.swing.JTextField();
        drugNameJLabel1 = new javax.swing.JLabel();
        expiryDateJTextField = new javax.swing.JTextField();
        clearJButton = new javax.swing.JButton();
        batchNumberJTextField = new javax.swing.JTextField();
        addToSuspectListJButton = new javax.swing.JButton();
        manufacturerNameJLabel2 = new javax.swing.JLabel();
        adverseEventJTextField = new javax.swing.JTextField();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        enterpriseNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        organizationNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        organizationNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        organizationNameJLabel.setPreferredSize(new java.awt.Dimension(190, 24));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("Suspect Drug");

        manufacturerNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel.setText("Unique ID");

        drugNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        drugNameJLabel.setText("Drug Name");

        statusJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        statusJLabel.setText("Manufacturer Name");

        uniqueIDJTextField.setEditable(false);
        uniqueIDJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        uniqueIDJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        uniqueIDJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        drugNameJTextField.setEditable(false);
        drugNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        drugNameJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        drugNameJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        manufacturerNameJTextField.setEditable(false);
        manufacturerNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        manufacturerNameJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        manufacturerNameJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        backJButton.setText("Back");
        backJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        manufacturerNameJLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel1.setText("Batch Number");

        manufacturerNameJLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel3.setText("Manufacturing Date");

        manufacturingDateJTextField.setEditable(false);
        manufacturingDateJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        manufacturingDateJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        manufacturingDateJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        drugNameJLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        drugNameJLabel1.setText("Expiry Date");

        expiryDateJTextField.setEditable(false);
        expiryDateJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        expiryDateJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        expiryDateJTextField.setPreferredSize(new java.awt.Dimension(147, 26));
        expiryDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateJTextFieldActionPerformed(evt);
            }
        });

        clearJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        clearJButton.setText("Declare Clear");
        clearJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        batchNumberJTextField.setEditable(false);
        batchNumberJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        batchNumberJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        batchNumberJTextField.setPreferredSize(new java.awt.Dimension(147, 26));
        batchNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNumberJTextFieldActionPerformed(evt);
            }
        });

        addToSuspectListJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        addToSuspectListJButton.setText("Add To Suspect List");
        addToSuspectListJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToSuspectListJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        addToSuspectListJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToSuspectListJButtonActionPerformed(evt);
            }
        });

        manufacturerNameJLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel2.setText("Adverse Event");

        adverseEventJTextField.setEditable(false);
        adverseEventJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        adverseEventJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        adverseEventJTextField.setPreferredSize(new java.awt.Dimension(147, 26));
        adverseEventJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adverseEventJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(businessNameJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(manufacturerNameJLabel)
                                    .addComponent(drugNameJLabel)
                                    .addComponent(statusJLabel)
                                    .addComponent(manufacturerNameJLabel3)
                                    .addComponent(drugNameJLabel1)
                                    .addComponent(manufacturerNameJLabel1)
                                    .addComponent(manufacturerNameJLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(batchNumberJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(expiryDateJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manufacturingDateJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drugNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uniqueIDJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adverseEventJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(titleJLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToSuspectListJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(businessNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleJLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerNameJLabel)
                    .addComponent(uniqueIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturingDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugNameJLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adverseEventJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToSuspectListJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void expiryDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateJTextFieldActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // TODO add your handling code here:
        
        addToSuspectListJButton.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Suspected Drug Has No Effects");
        JOptionPane.showMessageDialog(null, "Declared As Clear Drug");
              
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void batchNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNumberJTextFieldActionPerformed

    private void addToSuspectListJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToSuspectListJButtonActionPerformed
        // TODO add your handling code here:
        clearJButton.setEnabled(false);
        JOptionPane.showMessageDialog(null, "More Investigation Required");
        JOptionPane.showMessageDialog(null, "Drug Added To Suspected Drug List");
        selectedEnterprise.getSuspectPackageList().add(request.getSuspectDrug().getMedicinePackage());
        selectedEnterprise.getSuspectDrugList().add(request.getSuspectDrug().getMedicinePackage().getBatch().getDrug());
    }//GEN-LAST:event_addToSuspectListJButtonActionPerformed

    private void adverseEventJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adverseEventJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adverseEventJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToSuspectListJButton;
    private javax.swing.JTextField adverseEventJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField batchNumberJTextField;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JButton clearJButton;
    private javax.swing.JLabel drugNameJLabel;
    private javax.swing.JLabel drugNameJLabel1;
    private javax.swing.JTextField drugNameJTextField;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JTextField expiryDateJTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manufacturerNameJLabel;
    private javax.swing.JLabel manufacturerNameJLabel1;
    private javax.swing.JLabel manufacturerNameJLabel2;
    private javax.swing.JLabel manufacturerNameJLabel3;
    private javax.swing.JTextField manufacturerNameJTextField;
    private javax.swing.JTextField manufacturingDateJTextField;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel organizationNameJLabel;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JTextField uniqueIDJTextField;
    // End of variables declaration//GEN-END:variables
}
