/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government.SeniorManager;

import Business.Drug;
import Business.Enterprises.Enterprise;
import Business.Enterprises.Government;
import Business.Enterprises.Manufacturer;
import Business.MedicinePackage;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayank
 */
public class ViewSuspectListJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Government selectedEnterprise;
    UserAccount userAccount;
    Network selectedNetwork;

    /**
     * Creates new form OrderDrugsJPanel
     */
    public ViewSuspectListJPanel(JPanel userProcessContainer, Enterprise selectedEnterprise, UserAccount userAccount, Network selectedNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.selectedEnterprise = (Government) selectedEnterprise;
        this.userAccount = userAccount;
        this.selectedNetwork = selectedNetwork;

        enterpriseNameJLabel.setText(" --  " + selectedEnterprise.getEnterpriseName());
        networkNameJLabel.setText(selectedNetwork.getNetworkName());

        Organization organization = selectedEnterprise.getMyOrganization(userAccount);
        organizationNameJLabel.setText(organization.getOrganizationName());

        refreshSuspectList();
    }

    public void refreshSuspectList() {

        int rowCount = suspectDrugJTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) suspectDrugJTable.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }


        for (MedicinePackage mp : selectedEnterprise.getSuspectPackageList()) {
            Object row[] = new Object[4];
            row[0] = mp;
            row[1] = mp.getBatch().getDrug().getDrugName();
            row[2] = mp.getBatch().getBatchID();
            row[3] = mp.getBatch().getDrug().getManufacturerName();

            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        organizationNameJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suspectDrugJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        declareIllegitimateJButton = new javax.swing.JButton();
        networkNameJLabel = new javax.swing.JLabel();
        declareCleanJButton = new javax.swing.JButton();
        sendAlertJButton = new javax.swing.JButton();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        enterpriseNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        organizationNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        organizationNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        organizationNameJLabel.setPreferredSize(new java.awt.Dimension(190, 24));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("Suspect List");

        suspectDrugJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Unique ID", "Drug Name", "Batch ID", "Manufacturer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(suspectDrugJTable);
        suspectDrugJTable.getColumnModel().getColumn(0).setPreferredWidth(12);
        suspectDrugJTable.getColumnModel().getColumn(1).setPreferredWidth(15);
        suspectDrugJTable.getColumnModel().getColumn(3).setPreferredWidth(12);

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        declareIllegitimateJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        declareIllegitimateJButton.setText("Declare Illegitimate");
        declareIllegitimateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declareIllegitimateJButtonActionPerformed(evt);
            }
        });

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        declareCleanJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        declareCleanJButton.setText("Declare Clean");
        declareCleanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declareCleanJButtonActionPerformed(evt);
            }
        });

        sendAlertJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        sendAlertJButton.setText("Send Alert");
        sendAlertJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAlertJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(businessNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                        .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(titleJLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(declareCleanJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(declareIllegitimateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sendAlertJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(businessNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleJLabel)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(declareIllegitimateJButton)
                    .addComponent(declareCleanJButton))
                .addGap(18, 18, 18)
                .addComponent(sendAlertJButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void declareIllegitimateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declareIllegitimateJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = suspectDrugJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Package");
            return;
        }

        ArrayList<MedicinePackage> tempList = new ArrayList<>();

        MedicinePackage mp = (MedicinePackage) suspectDrugJTable.getValueAt(selectedRow, 0);
        Drug drug = mp.getBatch().getDrug();

        selectedEnterprise.getIllegitimateDrugList().add(drug);

        for (MedicinePackage m : selectedEnterprise.getSuspectPackageList()) {
            if (m.getBatch().getDrug() == drug) {
                tempList.add(m);
            }
        }

        for (MedicinePackage m : tempList) {
            selectedEnterprise.getSuspectPackageList().remove(m);
        }
        
        refreshSuspectList();

        JOptionPane.showMessageDialog(null, "Selected Drug Added To Illegitimate Drug List");

    }//GEN-LAST:event_declareIllegitimateJButtonActionPerformed

    private void declareCleanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declareCleanJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = suspectDrugJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Package");
            return;
        }

        MedicinePackage mp = (MedicinePackage) suspectDrugJTable.getValueAt(selectedRow, 0);
        
        selectedEnterprise.getSuspectPackageList().remove(mp);
        JOptionPane.showMessageDialog(null, "Package Declared Clear And Removed From Suspect List");
        
        refreshSuspectList();
    }//GEN-LAST:event_declareCleanJButtonActionPerformed

    private void sendAlertJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAlertJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = suspectDrugJTable.getSelectedRow();
        
        MedicinePackage mp = (MedicinePackage)suspectDrugJTable.getValueAt(selectedRow, 0);
        
        ArrayList<Enterprise> entList = Business.Business.getInstance().getEnterpriseList(Enterprise.Type.MANUFACTURER);
        
        for(Enterprise e : entList) {
            Manufacturer m = (Manufacturer)e;
            if(m.getEnterpriseName().equals(mp.getBatch().getDrug().getManufacturerName())) {
                m.setFlag(false);
                m.setAlertMessage("'" + mp.getUniqueID() + "' Package Is Declared Suspect");
            }
        }
        
        for(Network n : Business.Business.getInstance().getNetworkDirectory().getNetworkList()) {
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for(Enterprise ee : entList) {
                    if(!(e==ee)) {
                        e.setFlag(false);
                        e.setAlertMessage("'" + mp.getUniqueID() + "' Package Is Declared Suspect. It Belongs To Manufacturer '" + mp.getBatch().getDrug().getManufacturerName() + "' Manufacturer");
                    }
                }
                
            }
        }
        
    }//GEN-LAST:event_sendAlertJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JButton declareCleanJButton;
    private javax.swing.JButton declareIllegitimateJButton;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel organizationNameJLabel;
    private javax.swing.JButton sendAlertJButton;
    private javax.swing.JTable suspectDrugJTable;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
