/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Employee;
import Business.Enterprises.Enterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Person;
import Business.Roles.Role;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class AddEmployeeJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise selectedEnterprise;
    UserAccount userAccount;
    Network selectedNetwork;

    /**
     * Creates new form AddEmployeeJPanel
     */
    public AddEmployeeJPanel(JPanel userProcessContainer, Enterprise selectedEnterprise, UserAccount userAccount, Network selectedNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.selectedEnterprise = selectedEnterprise;
        this.userAccount = userAccount;
        this.selectedNetwork = selectedNetwork;
        
        networkNameJLabel.setText(selectedNetwork.getNetworkName());
        enterpriseNameJLabel.setText(" --  " + selectedEnterprise.getEnterpriseName());
        
        organizationTypeJComboBox.removeAllItems();
        organizationTypeJComboBox.addItem("Select Organization");
        for(Organization o : selectedEnterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationTypeJComboBox.addItem(o);
        }
        
        employeeJComboBox.removeAllItems();
        employeeJComboBox.addItem("Select Employee");
        for(Person person : selectedEnterprise.getPersonDirectory().getPersonList()) {
            employeeJComboBox.addItem(person);
        }
        
        roleJComboBox.removeAllItems();
        roleJComboBox.addItem("Select Role");
        for(Role role : selectedEnterprise.getSupportedRoles()) {
            roleJComboBox.addItem(role);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titleJLabel = new javax.swing.JLabel();
        organizationDetailJLabel = new javax.swing.JLabel();
        organizationTypeJLabel = new javax.swing.JLabel();
        userAccountDetailJLabel = new javax.swing.JLabel();
        employeeJLabel = new javax.swing.JLabel();
        userNameJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        roleJLabel = new javax.swing.JLabel();
        organizationTypeJComboBox = new javax.swing.JComboBox();
        employeeJComboBox = new javax.swing.JComboBox();
        userNameJTextField = new javax.swing.JTextField();
        passwordJPasswordField = new javax.swing.JPasswordField();
        roleJComboBox = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        createManagerJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        designationJTextField = new javax.swing.JTextField();
        designationJLabel = new javax.swing.JLabel();
        employeeDetailJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseNameJLabel.setPreferredSize(new java.awt.Dimension(150, 10));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("Create Employee");

        organizationDetailJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        organizationDetailJLabel.setText("Organization Detail");

        organizationTypeJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        organizationTypeJLabel.setText("Organization Type");

        userAccountDetailJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userAccountDetailJLabel.setText("User Account Detail");

        employeeJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        employeeJLabel.setText("Employee");

        userNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        userNameJLabel.setText("Username");

        passwordJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        passwordJLabel.setText("Password");

        roleJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        roleJLabel.setText("Role");

        organizationTypeJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        organizationTypeJComboBox.setMinimumSize(new java.awt.Dimension(170, 26));
        organizationTypeJComboBox.setPreferredSize(new java.awt.Dimension(170, 26));

        employeeJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        employeeJComboBox.setMinimumSize(new java.awt.Dimension(170, 26));
        employeeJComboBox.setPreferredSize(new java.awt.Dimension(170, 26));

        userNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        userNameJTextField.setMinimumSize(new java.awt.Dimension(170, 26));
        userNameJTextField.setPreferredSize(new java.awt.Dimension(170, 26));

        passwordJPasswordField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        passwordJPasswordField.setMinimumSize(new java.awt.Dimension(170, 26));
        passwordJPasswordField.setPreferredSize(new java.awt.Dimension(170, 26));

        roleJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        roleJComboBox.setMinimumSize(new java.awt.Dimension(170, 26));
        roleJComboBox.setPreferredSize(new java.awt.Dimension(170, 26));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        backJButton.setText("Back");
        backJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        createManagerJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        createManagerJButton.setText("Create");
        createManagerJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createManagerJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        createManagerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createManagerJButtonActionPerformed(evt);
            }
        });

        clearJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        clearJButton.setText("Clear");
        clearJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        designationJTextField.setMinimumSize(new java.awt.Dimension(100, 25));
        designationJTextField.setPreferredSize(new java.awt.Dimension(100, 25));

        designationJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        designationJLabel.setText("Designation");

        employeeDetailJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        employeeDetailJLabel.setText("Employee Detail");

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(businessNameJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(organizationDetailJLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(employeeDetailJLabel))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(organizationTypeJLabel)
                                .addComponent(employeeJLabel)
                                .addComponent(designationJLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(designationJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(organizationTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(userAccountDetailJLabel)
                            .addGap(288, 288, 288))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(userNameJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(passwordJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(roleJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(createManagerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(titleJLabel)
                        .addGap(107, 107, 107)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(businessNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleJLabel)
                .addGap(30, 30, 30)
                .addComponent(organizationDetailJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationTypeJLabel))
                .addGap(23, 23, 23)
                .addComponent(employeeDetailJLabel)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designationJLabel))
                .addGap(17, 17, 17)
                .addComponent(userAccountDetailJLabel)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleJLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createManagerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createManagerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createManagerJButtonActionPerformed
        // TODO add your handling code here:

        if (organizationTypeJComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select Organization Type");
            return;
        }
        
        if (employeeJComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select Employee");
            return;
        }
        
        if (designationJTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Designation");
            return;
        }

        if (userNameJTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter User Name");
            return;
        }

        if (passwordJPasswordField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Password");
            return;
        }
        
        if(roleJComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select Role");
            return;
        }

        Organization organization = (Organization)organizationTypeJComboBox.getSelectedItem();
        Person person = (Person)employeeJComboBox.getSelectedItem();
        Employee employee = organization.getEmployeeDirectory().newEmployee();
        employee.setDesignation(designationJTextField.getText());
        employee.setPerson(person);
        
        UserAccount ua = organization.getUserAccountDirectory().newUserAccount();

        ua.setUserName(userNameJTextField.getText());
        char[] pass = passwordJPasswordField.getPassword();
        String password = String.valueOf(pass);
        ua.setPassword(password);
        ua.setEmployee(employee);
        Role role = (Role)roleJComboBox.getSelectedItem();
        ua.setRole(role);


        organizationTypeJComboBox.setEnabled(false);
        employeeJComboBox.setEnabled(false);
        designationJTextField.setEditable(false);
        userNameJTextField.setEditable(false);
        passwordJPasswordField.setEditable(false);
        roleJComboBox.setEnabled(false);
        createManagerJButton.setEnabled(false);

    }//GEN-LAST:event_createManagerJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // TODO add your handling code here:

        organizationTypeJComboBox.setEnabled(true);
        employeeJComboBox.setEnabled(true);
        designationJTextField.setEditable(true);
        userNameJTextField.setEditable(true);
        passwordJPasswordField.setEditable(true);
        roleJComboBox.setEnabled(true);

        organizationTypeJComboBox.setSelectedIndex(0);
        employeeJComboBox.setSelectedIndex(0);
        designationJTextField.setText("");
        userNameJTextField.setText("");
        passwordJPasswordField.setText("");
        roleJComboBox.setSelectedIndex(0);
        createManagerJButton.setEnabled(true);
    }//GEN-LAST:event_clearJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JButton clearJButton;
    private javax.swing.JButton createManagerJButton;
    private javax.swing.JLabel designationJLabel;
    private javax.swing.JTextField designationJTextField;
    private javax.swing.JLabel employeeDetailJLabel;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JLabel employeeJLabel;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel organizationDetailJLabel;
    private javax.swing.JComboBox organizationTypeJComboBox;
    private javax.swing.JLabel organizationTypeJLabel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JLabel roleJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel userAccountDetailJLabel;
    private javax.swing.JLabel userNameJLabel;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
