/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.Enterprises.Enterprise;
import Business.Enterprises.Government;
import Business.Network.Network;
import Business.UserAccount;
import Business.WorkRequest.ApplyForLicenseWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class EnterpriseAdminWorkAreaForLicenseJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise selectedEnterprise;
    UserAccount userAccount;
    Network selectedNetwork;
    Business business;
    
    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     */
    public EnterpriseAdminWorkAreaForLicenseJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        business = Business.getInstance();
        
        selectedNetwork = business.getNetworkDirectory().getMyNetwork(userAccount);
        selectedEnterprise = selectedNetwork.getEnterpriseDirectory().getMyEnterprise(userAccount);
        
        networkNameJLabel.setText(selectedNetwork.getNetworkName());
        enterpriseTypeJLabel.setText(" --  " + selectedEnterprise.getEnterpriseName());        
        nameJLabel.setText(userAccount.getEmployee().getPerson().getFirstName() + " " + userAccount.getEmployee().getPerson().getLastName() + " -- ");
        
        if(selectedEnterprise.getLicenseCount() == 0) {
            applyForLicenseJButton.setEnabled(true);
        }
        else if(selectedEnterprise.getLicenseCount() == -1) {
            JOptionPane.showMessageDialog(null, "License Request Rejected. Resend an Updated Request");
            selectedEnterprise.setLicenseCount(0);
            applyForLicenseJButton.setEnabled(true);
        }
        else if(selectedEnterprise.getLicenseCount() == -2) {
            JOptionPane.showMessageDialog(null, "License Expired. Reapply For License");
            selectedEnterprise.setLicenseCount(0);
            applyForLicenseJButton.setEnabled(true);

        }
        else {
            JOptionPane.showMessageDialog(null, "License Approval Request Already Sent. Wait For Approval From Law Agency");
            userProcessContainer.remove(this);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.previous(userProcessContainer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameJLabel = new javax.swing.JLabel();
        enterpriseTypeJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        applyForLicenseJButton = new javax.swing.JButton();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseTypeJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseTypeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseTypeJLabel.setPreferredSize(new java.awt.Dimension(150, 10));

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        nameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("My Work Area");

        applyForLicenseJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        applyForLicenseJButton.setText("Apply for License");
        applyForLicenseJButton.setEnabled(false);
        applyForLicenseJButton.setMaximumSize(new java.awt.Dimension(250, 37));
        applyForLicenseJButton.setMinimumSize(new java.awt.Dimension(250, 37));
        applyForLicenseJButton.setPreferredSize(new java.awt.Dimension(250, 37));
        applyForLicenseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyForLicenseJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(businessNameJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterpriseTypeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(applyForLicenseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(businessNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterpriseTypeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleJLabel)
                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(applyForLicenseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyForLicenseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyForLicenseJButtonActionPerformed
        // TODO add your handling code here:
        ApplyForLicenseWorkRequest request;
        
        Government govt = (Government)selectedNetwork.getEnterpriseDirectory().getSelectedEnterprise(Enterprise.Type.GOVERNMENT);
        
        if(selectedEnterprise.getEnterpriseType().equals(Enterprise.Type.MANUFACTURER.toString())) {
            request = (ApplyForLicenseWorkRequest)govt.getGovernmentFederalLicenseManagementOrganization().getWorkQueue().newWorkRequest(WorkRequest.Type.ApplyForLicenseRequest); 
            JOptionPane.showMessageDialog(null, "Application For License Approval Sent To Federal Licensing Organization");
        }
        
        else {
            request = (ApplyForLicenseWorkRequest)govt.getGovernmentStateLevelLicensingOrganization().getWorkQueue().newWorkRequest(WorkRequest.Type.ApplyForLicenseRequest);
            JOptionPane.showMessageDialog(null, "Application For License Approval Sent To State Level Licensing Organization");
        }

        
        SimpleDateFormat sdf = new SimpleDateFormat("MM dd yy HH:mm:ss");
        String currentDate = sdf.format(new Date());
        request.setRequestDate(currentDate);
        request.setSender(userAccount);
        request.setStatus(WorkRequest.Status.ForApproval);
        request.setDecision(ApplyForLicenseWorkRequest.status.PENDING.toString());
        
        selectedEnterprise.setLicenseCount(selectedEnterprise.getLicenseCount()+1);
        applyForLicenseJButton.setEnabled(false);
        
                     
    }//GEN-LAST:event_applyForLicenseJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyForLicenseJButton;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JLabel enterpriseTypeJLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
