/*
 * PlaceOrderJPanel.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package UserInterface.HospitalPortal;

import Business.Drug;
import Business.Enterprises.Enterprise;
import Business.Enterprises.Government;
import Business.Enterprises.Hospital;
import Business.InventoryItem;
import Business.MedicinePackage;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Patient;
import Business.SuspectPackage;
import Business.UserAccount;
import Business.VisitRecord;
import Business.WorkRequest.SuspectPackageWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayank
 */
public class ReportSuspectPackageJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Hospital selectedEnterprise;
    UserAccount userAccount;
    Network selectedNetwork;
    SuspectPackage tempSuspectPackage;
    int selectedRow;
    Patient patient;
    Drug drug;

    /**
     * Creates new form PlaceOrderJPanel
     */
    public ReportSuspectPackageJPanel(JPanel userProcessContainer, Enterprise selectedEnterprise, UserAccount userAccount, Network selectedNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.selectedEnterprise = (Hospital) selectedEnterprise;
        this.userAccount = userAccount;
        this.selectedNetwork = selectedNetwork;
        
        tempSuspectPackage = new SuspectPackage();
        
        networkNameJLabel.setText(selectedNetwork.getNetworkName());
        
        
    }
    
    private void refreshPatientHistoryList(Patient patient) {
        
        int rowCount = prescriptionListJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) prescriptionListJTable.getModel()).removeRow(i);
        }
        
        for (VisitRecord vr : patient.getPatientHistory().getVisitRecordList()) {
            for (InventoryItem ii : vr.getInventory().getInventoryItemList()) {
                Object row[] = new Object[3];
                row[0] = ii.getDrug();
                row[1] = ii;
                row[2] = vr.getDateOfVisit();
//                TableColumn uniqueId = prescriptionListJTable.getColumnModel().getColumn(3);
//                JComboBox uniqueIDJComboBox = new JComboBox();
//                for (MedicinePackage mp : ii.getMedicinePackageList()) {
//                    uniqueIDJComboBox.addItem(mp);
//                }
//                uniqueId.setCellEditor(new DefaultCellEditor(uniqueIDJComboBox));
                ((DefaultTableModel) prescriptionListJTable.getModel()).addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        organizationNameJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        titleJLabel = new javax.swing.JLabel();
        patientNameJLabel = new javax.swing.JLabel();
        prescriptionTitleJLabel = new javax.swing.JLabel();
        suspectDrugsTitleJLabel = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionListJTable = new javax.swing.JTable();
        selectSuspectJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        suspectDrugsListJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        reportJButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        suspectDrugsTitleJLabel1 = new javax.swing.JLabel();
        selectPackageJButton = new javax.swing.JButton();
        goJButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 511));

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        enterpriseNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        organizationNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        organizationNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        organizationNameJLabel.setPreferredSize(new java.awt.Dimension(190, 24));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("Report Suspect Drug");

        patientNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        patientNameJLabel.setText("Patient Name");

        prescriptionTitleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        prescriptionTitleJLabel.setText("Prescription History");

        suspectDrugsTitleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        suspectDrugsTitleJLabel.setText("Selected Suspect Drug");

        patientNameJTextField.setMinimumSize(new java.awt.Dimension(150, 28));
        patientNameJTextField.setPreferredSize(new java.awt.Dimension(150, 28));

        prescriptionListJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prescriptionListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Drug Quantity", "Date Of Prescription"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prescriptionListJTable);

        selectSuspectJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        selectSuspectJButton.setText("Select Drug");
        selectSuspectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSuspectJButtonActionPerformed(evt);
            }
        });

        suspectDrugsListJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suspectDrugsListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Unique ID", "Drug Name", "Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(suspectDrugsListJTable);

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        reportJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        reportJButton.setText("Report");
        reportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButtonActionPerformed(evt);
            }
        });

        suspectDrugsTitleJLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        suspectDrugsTitleJLabel1.setText("Select medicine Package");

        selectPackageJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        selectPackageJButton.setText("Select Package");
        selectPackageJButton.setEnabled(false);
        selectPackageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPackageJButtonActionPerformed(evt);
            }
        });

        goJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        goJButton.setText("GO");
        goJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(businessNameJLabel)
                        .addGap(6, 6, 6)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prescriptionTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suspectDrugsTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(suspectDrugsTitleJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectPackageJButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reportJButton))
                        .addComponent(selectSuspectJButton)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(titleJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(patientNameJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(businessNameJLabel)
                    .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(titleJLabel)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameJLabel)
                    .addComponent(patientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goJButton))
                .addGap(18, 18, 18)
                .addComponent(prescriptionTitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectSuspectJButton)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suspectDrugsTitleJLabel1)
                    .addComponent(selectPackageJButton))
                .addGap(41, 41, 41)
                .addComponent(suspectDrugsTitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(reportJButton))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButtonActionPerformed
        // TODO add your handling code here:
Government govt = (Government) selectedNetwork.getEnterpriseDirectory().getSelectedEnterprise(Enterprise.Type.GOVERNMENT);
        
        SuspectPackageWorkRequest request = (SuspectPackageWorkRequest) govt.getComplaintHandlingOrganization().getWorkQueue().newWorkRequest(WorkRequest.Type.SuspectPackageWorkRequest);
        
        SimpleDateFormat sdf = new SimpleDateFormat("MM dd yy HH:mm:ss");
        Date date = new Date();
        String currentDate = sdf.format(date);
        request.setSuspectPackage(tempSuspectPackage);
        request.setRequestDate(currentDate);
        request.setSender(userAccount);
        request.setStatus(WorkRequest.Status.SuspectPackageComplaint);
        
        Organization o = selectedEnterprise.getMyOrganization(userAccount);
        o.getSentWorkQueue().addRequest(request);
        
        JOptionPane.showMessageDialog(null, "Suspect Package Reported To FDA");
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_reportJButtonActionPerformed
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed
    
    private void selectSuspectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSuspectJButtonActionPerformed
        // TODO add your handling code here:
        selectedRow = prescriptionListJTable.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Drug To Add It To The Suspect Package List");
            return;
        }
        
        InventoryItem ii= (InventoryItem)prescriptionListJTable.getValueAt(selectedRow, 1);
        
        jComboBox1.removeAllItems();
        for(MedicinePackage mp : ii.getMedicinePackageList()) {
            jComboBox1.addItem(mp);
        }
        
        selectPackageJButton.setEnabled(true);
        
        
        
        
        
        
    }//GEN-LAST:event_selectSuspectJButtonActionPerformed

    private void selectPackageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPackageJButtonActionPerformed
        // TODO add your handling code here:
        MedicinePackage mp = (MedicinePackage) jComboBox1.getSelectedItem();

       tempSuspectPackage.setMedicinePackage(mp);
        
        
        String detail = JOptionPane.showInputDialog(null, "Enter Suspect Package Details");
        tempSuspectPackage.setDetails(detail);
        
        
        Object row[] = new Object[3];
        row[0] = tempSuspectPackage.getMedicinePackage();
        row[1] = tempSuspectPackage.getMedicinePackage().getBatch().getDrug().getDrugName();
        row[2] = tempSuspectPackage.getDetails();
        
        ((DefaultTableModel) suspectDrugsListJTable.getModel()).addRow(row);
        
        selectSuspectJButton.setEnabled(false);
        selectPackageJButton.setEnabled(false);
    }//GEN-LAST:event_selectPackageJButtonActionPerformed

    private void goJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJButtonActionPerformed
        // TODO add your handling code here:
        String patientName = patientNameJTextField.getText();
        
        ArrayList<Enterprise> entList = Business.Business.getInstance().getEnterpriseList(Enterprise.Type.HOSPITAL);
        
        for(Enterprise e : entList) {
            Hospital h = (Hospital)e;
            
            for(Patient p : h.getPatientDirectory().getPatientList()) {
                if(p.getPerson().getFirstName().equalsIgnoreCase(patientName)) {
                    patient = p;
                }
            }
            
        }
        
        refreshPatientHistoryList(patient);
    }//GEN-LAST:event_goJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JButton goJButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel organizationNameJLabel;
    private javax.swing.JLabel patientNameJLabel;
    private javax.swing.JTextField patientNameJTextField;
    private javax.swing.JTable prescriptionListJTable;
    private javax.swing.JLabel prescriptionTitleJLabel;
    private javax.swing.JButton reportJButton;
    private javax.swing.JButton selectPackageJButton;
    private javax.swing.JButton selectSuspectJButton;
    private javax.swing.JTable suspectDrugsListJTable;
    private javax.swing.JLabel suspectDrugsTitleJLabel;
    private javax.swing.JLabel suspectDrugsTitleJLabel1;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
