/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TrackingPortal;

import Business.Business;
import Business.Drug;
import Business.Enterprises.Enterprise;
import Business.Enterprises.Government;
import Business.Enterprises.Manufacturer;
import Business.MedicinePackage;
import Business.Network.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class TrackingPortalJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    Business business;
    Network selectedNetwork;
    int uniqueID;
    Government govt;
    boolean flag;
    MedicinePackage medicinePackage;

    /**
     * Creates new form InventoryManagerJPanel
     */
    public TrackingPortalJPanel(JPanel userProcessContainer, UserAccount userAccount, Network selectedNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.selectedNetwork = selectedNetwork;

        business = Business.getInstance();

        govt = (Government) selectedNetwork.getEnterpriseDirectory().getSelectedEnterprise(Enterprise.Type.GOVERNMENT);
        flag = true;
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        businessNameJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        titleJLabel = new javax.swing.JLabel();
        goJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        drugNameJLabel = new javax.swing.JLabel();
        drugNameJTextField = new javax.swing.JTextField();
        statusJLabel = new javax.swing.JLabel();
        manufacturerNameJTextField = new javax.swing.JTextField();
        manufacturerNameJLabel3 = new javax.swing.JLabel();
        manufacturingDateJTextField = new javax.swing.JTextField();
        drugNameJLabel1 = new javax.swing.JLabel();
        expiryDateJTextField = new javax.swing.JTextField();
        manufacturerNameJLabel1 = new javax.swing.JLabel();
        batchNumberJTextField = new javax.swing.JTextField();
        viewTransactionDetailsJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        manufacturerNameJLabel2 = new javax.swing.JLabel();
        uniqueIDJTextField = new javax.swing.JTextField();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("Tracking Portal");

        goJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        goJButton.setText("GO");
        goJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        goJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        goJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        goJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJButtonActionPerformed(evt);
            }
        });

        drugNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        drugNameJLabel.setText("Drug Name");

        drugNameJTextField.setEditable(false);
        drugNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        drugNameJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        drugNameJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        statusJLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        statusJLabel.setText("Manufacturer Name");

        manufacturerNameJTextField.setEditable(false);
        manufacturerNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        manufacturerNameJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        manufacturerNameJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        manufacturerNameJLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel3.setText("Manufacturing Date");

        manufacturingDateJTextField.setEditable(false);
        manufacturingDateJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        manufacturingDateJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        manufacturingDateJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        drugNameJLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        drugNameJLabel1.setText("Expiry Date");

        expiryDateJTextField.setEditable(false);
        expiryDateJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        expiryDateJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        expiryDateJTextField.setPreferredSize(new java.awt.Dimension(147, 26));
        expiryDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateJTextFieldActionPerformed(evt);
            }
        });

        manufacturerNameJLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel1.setText("Batch Number");

        batchNumberJTextField.setEditable(false);
        batchNumberJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        batchNumberJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        batchNumberJTextField.setPreferredSize(new java.awt.Dimension(147, 26));
        batchNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNumberJTextFieldActionPerformed(evt);
            }
        });

        viewTransactionDetailsJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewTransactionDetailsJButton.setText("View Transaction Detail");
        viewTransactionDetailsJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        viewTransactionDetailsJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        viewTransactionDetailsJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        viewTransactionDetailsJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewTransactionDetailsJButtonMouseReleased(evt);
            }
        });
        viewTransactionDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionDetailsJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        backJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        backJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(drugNameJLabel)
                            .addComponent(statusJLabel)
                            .addComponent(manufacturerNameJLabel3)
                            .addComponent(drugNameJLabel1)
                            .addComponent(manufacturerNameJLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(batchNumberJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiryDateJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manufacturingDateJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drugNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewTransactionDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturingDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugNameJLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerNameJLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTransactionDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        manufacturerNameJLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        manufacturerNameJLabel2.setText("Unique ID");

        uniqueIDJTextField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        uniqueIDJTextField.setMinimumSize(new java.awt.Dimension(147, 26));
        uniqueIDJTextField.setPreferredSize(new java.awt.Dimension(147, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(businessNameJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(titleJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manufacturerNameJLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uniqueIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(goJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(businessNameJLabel)
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleJLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerNameJLabel2)
                    .addComponent(uniqueIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJButtonActionPerformed
        // TODO add your handling code here:
        
        try {
              Integer.parseInt(uniqueIDJTextField.getText());
            } catch (NumberFormatException nfe) {
                     JOptionPane.showMessageDialog(null, "Invalid UniqueID");
                     return;    
            }
        
        if((uniqueIDJTextField.getText()).equals("")) {
            JOptionPane.showMessageDialog(null, "Enter UniqueID");
            return;
        }
        
        uniqueID = (Integer.parseInt(uniqueIDJTextField.getText()));

        if (!govt.getIllegitimateDrugList().isEmpty()) {
            boolean flag1 = true;
            ArrayList<Enterprise> entList = Business.getInstance().getEnterpriseList(Enterprise.Type.MANUFACTURER);
            
            
            for(Enterprise e : entList) {
                Manufacturer m = (Manufacturer)e;
                
                for(MedicinePackage mp : m.getManufacturedMedicinePackages()) {
                    if(mp.getUniqueID() == uniqueID) {
                        medicinePackage = mp;
                        flag1 = false;
                        break;
                    }
                }
                if(flag1 == false) {
                    break;
                }
            }
            
            for (Drug drug : govt.getIllegitimateDrugList()) {
                if (medicinePackage.getBatch().getDrug() == drug) {
                    JOptionPane.showMessageDialog(null, "This Is Illegitimate Drug");
                    JOptionPane.showMessageDialog(null, "Transaction History Cannot Be Seen");
                    JOptionPane.showMessageDialog(null, "Dispose This Package Immediately And File A Report Against The Selling Enterprise");
                    flag = false;
                }
            }
        }

        if (flag) {
            if (!govt.getSuspectPackageList().isEmpty()) {
                for (MedicinePackage mp : govt.getSuspectPackageList()) {
                    if (mp.getUniqueID() == uniqueID) {
                        JOptionPane.showMessageDialog(null, "This Is Suspect Package");
                        JOptionPane.showMessageDialog(null, "Transaction History Cannot Be Seen");
                        JOptionPane.showMessageDialog(null, "Dispose This Package Immediately And File A Report Against The Selling Enterprise");
                        flag = false;
                    }
                }
            }
        }
        
        if(flag) {
            if (!govt.getTheftPackageList().isEmpty()) {
                for (MedicinePackage mp : govt.getTheftPackageList()) {
                    if (mp.getUniqueID() == uniqueID) {
                        JOptionPane.showMessageDialog(null, "This Is Theft Package");
                        JOptionPane.showMessageDialog(null, "Transaction History Cannot Be Seen");
                        JOptionPane.showMessageDialog(null, "Dispose This Package Immediately And File A Report Against The Selling Enterprise");
                        flag = false;
                    }
                }
            }
        }
        boolean flag1 = true;
        
        if(flag) {
            ArrayList<Enterprise> entList = Business.getInstance().getEnterpriseList(Enterprise.Type.MANUFACTURER);
            
            
            for(Enterprise e : entList) {
                Manufacturer m = (Manufacturer)e;
                
                for(MedicinePackage mp : m.getManufacturedMedicinePackages()) {
                    if(mp.getUniqueID() == uniqueID) {
                        medicinePackage = mp;
                        flag1 = false;
                        break;
                    }
                }
                if(flag1 == false) {
                    break;
                }
            }
            
            jPanel1.setVisible(true);
            
            flag = false;
            drugNameJTextField.setText(medicinePackage.getBatch().getDrug().getDrugName());
            manufacturerNameJTextField.setText(medicinePackage.getBatch().getDrug().getManufacturerName());
            manufacturingDateJTextField.setText(medicinePackage.getBatch().getManufacturingDate());
            expiryDateJTextField.setText(medicinePackage.getBatch().getExpiryDate());
            batchNumberJTextField.setText(String.valueOf(medicinePackage.getBatch().getBatchID()));
        }
        
        if(flag) {
            JOptionPane.showMessageDialog(null, "No Match Found");
        }



    }//GEN-LAST:event_goJButtonActionPerformed

    private void expiryDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateJTextFieldActionPerformed

    private void batchNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNumberJTextFieldActionPerformed

    private void viewTransactionDetailsJButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTransactionDetailsJButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTransactionDetailsJButtonMouseReleased

    private void viewTransactionDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionDetailsJButtonActionPerformed
        // TODO add your handling code here:
        
        ViewTransactionHistoryJPanel viewTransactionHistoryJPanel = new ViewTransactionHistoryJPanel(userProcessContainer, medicinePackage, selectedNetwork);
        userProcessContainer.add("ViewTransaction", viewTransactionHistoryJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewTransactionDetailsJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField batchNumberJTextField;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JLabel drugNameJLabel;
    private javax.swing.JLabel drugNameJLabel1;
    private javax.swing.JTextField drugNameJTextField;
    private javax.swing.JTextField expiryDateJTextField;
    private javax.swing.JButton goJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manufacturerNameJLabel1;
    private javax.swing.JLabel manufacturerNameJLabel2;
    private javax.swing.JLabel manufacturerNameJLabel3;
    private javax.swing.JTextField manufacturerNameJTextField;
    private javax.swing.JTextField manufacturingDateJTextField;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JTextField uniqueIDJTextField;
    private javax.swing.JButton viewTransactionDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
