/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Wholesaler.Shipping;

import Business.Business;
import Business.Enterprises.Enterprise;
import Business.Enterprises.Hospital;
import Business.Enterprises.Wholesaler;
import Business.InventoryItem;
import Business.MedicinePackage;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Transaction;
import Business.UserAccount;
import Business.WorkRequest.ReceiveShippmentWorkRequest;
import Business.WorkRequest.ShipWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayank
 */
public class ProcessShippmentJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Wholesaler selectedEnterprise;
    UserAccount userAccount;
    Network selectedNetwork;
    ShipWorkRequest request;
    ViewWorkQueueJPanel viewWorkQueueJPanel;
    Business business;
    Hospital hEnterprise;
    Network hNetwork;

    /**
     * Creates new form BusinessAdminJPanel
     */
    public ProcessShippmentJPanel(JPanel userProcessContainer, Enterprise selectedEnterprise, UserAccount userAccount, Network selectedNetwork, ShipWorkRequest request, ViewWorkQueueJPanel viewWorkQueueJPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.selectedEnterprise = (Wholesaler) selectedEnterprise;
        this.userAccount = userAccount;
        this.selectedNetwork = selectedNetwork;
        this.request = request;
        this.viewWorkQueueJPanel = (ViewWorkQueueJPanel) viewWorkQueueJPanel;

        business = Business.getInstance();

        refreshOrder();

        enterpriseNameJLabel.setText(" --  " + selectedEnterprise.getEnterpriseName());
        networkNameJLabel.setText(selectedNetwork.getNetworkName());

        Organization o = selectedEnterprise.getMyOrganization(userAccount);
        organizationNameJLabel.setText(o.getOrganizationName());

        hNetwork = business.getNetworkDirectory().getMyNetwork(request.getOrderDrugsWorkRequest().getSender());
        hEnterprise = (Hospital) hNetwork.getEnterpriseDirectory().getMyEnterprise(request.getOrderDrugsWorkRequest().getSender());
        wholesalerNameJLabel.setText(hEnterprise.getEnterpriseName());
    }

    private void refreshOrder() {


        int rowCount = orderJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) orderJTable.getModel()).removeRow(i);
        }

        for (InventoryItem ii : request.getInventory().getInventoryItemList()) {

            Object[] row = new Object[3];
            row[0] = ii.getDrug().getDrugId();
            row[1] = ii.getDrug().getDrugName();
            row[2] = ii;
            ((DefaultTableModel) orderJTable.getModel()).addRow(row);
//            getTableCellRendererComponent(inventoryJTable,batch , true, true, i, 3);

        }

    }

//    @Override
//    public Component getTableCellRendererComponent(
//            JTable table, Object value, boolean isSelected,boolean hasFocus, int row, int col) {
////        Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
//
//        int s = (Integer)table.getModel().getValueAt(row, col);
//
//        if (s < 10) {
//            setForeground(Color.red);
//        } else {
//            setForeground(null);
//        }
//            return this;
//        return super.getTableCellRendererComponent(table, value, true, true,row, col);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        organizationNameJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        viewDetailsJButton = new javax.swing.JButton();
        drugNameTitleJLabel = new javax.swing.JLabel();
        drugNameJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        wholesalerNameTitleJLabel = new javax.swing.JLabel();
        wholesalerNameJLabel = new javax.swing.JLabel();
        shipOrderJButton = new javax.swing.JButton();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        enterpriseNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        organizationNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        organizationNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        organizationNameJLabel.setPreferredSize(new java.awt.Dimension(190, 24));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("Process Shippment");

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderJTable);

        viewDetailsJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        viewDetailsJButton.setText("View Details");
        viewDetailsJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailsJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        viewDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButtonActionPerformed(evt);
            }
        });

        drugNameTitleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        drugNameTitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        drugNameTitleJLabel.setText("Drug Name");
        drugNameTitleJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        drugNameTitleJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        drugNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        drugNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        drugNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        drugNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        orderItemJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Unique ID", "MFG Date", "Expiry Date", "Batch ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderItemJTable);

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        backJButton.setText("Back");
        backJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        wholesalerNameTitleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        wholesalerNameTitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wholesalerNameTitleJLabel.setText("Hospital Name");
        wholesalerNameTitleJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        wholesalerNameTitleJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        wholesalerNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        wholesalerNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wholesalerNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        wholesalerNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        shipOrderJButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        shipOrderJButton.setText("Ship Order");
        shipOrderJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shipOrderJButton.setPreferredSize(new java.awt.Dimension(80, 30));
        shipOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipOrderJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(businessNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                        .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(titleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drugNameTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drugNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wholesalerNameTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wholesalerNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shipOrderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(viewDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(businessNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wholesalerNameTitleJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wholesalerNameJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drugNameTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipOrderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select A Row To View Details");
            return;
        }

        InventoryItem ii = (InventoryItem) orderJTable.getValueAt(selectedRow, 2);

        drugNameJLabel.setText(ii.getDrug().getDrugName());

        int rowCount = orderItemJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) orderItemJTable.getModel()).removeRow(i);
        }

        for (MedicinePackage mp : ii.getMedicinePackageList()) {
            Object row[] = new Object[4];
            row[0] = mp;
            row[1] = mp.getBatch().getManufacturingDate();
            row[2] = mp.getBatch().getExpiryDate();
            row[3] = mp.getBatch().getBatchID();
            ((DefaultTableModel) orderItemJTable.getModel()).addRow(row);
        }
    }//GEN-LAST:event_viewDetailsJButtonActionPerformed

    private void orderJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderJTableMouseClicked
        // TODO add your handling code here:

        int selectedRow = orderJTable.getSelectedRow();
        if (selectedRow < 0 || selectedRow > orderJTable.getRowCount()) {
            return;
        }

        int rowCount = orderItemJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) orderItemJTable.getModel()).removeRow(i);
        }
    }//GEN-LAST:event_orderJTableMouseClicked

    private void shipOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipOrderJButtonActionPerformed
        // TODO add your handling code here:
//        disEnterprise
        ReceiveShippmentWorkRequest receiveShippmentWorkRequest = (ReceiveShippmentWorkRequest) hEnterprise.getHospitalInventoryManagementOrganization().getWorkQueue().newWorkRequest(WorkRequest.Type.ReceiveShipmentWorkRequest);
        SimpleDateFormat sdf = new SimpleDateFormat("MM dd yy HH:mm:ss");
        String currentDate = sdf.format(new Date());
        receiveShippmentWorkRequest.setRequestDate(currentDate);
        receiveShippmentWorkRequest.setSender(userAccount);
        receiveShippmentWorkRequest.setShipWorkRequest(request);
        receiveShippmentWorkRequest.setStatus(WorkRequest.Status.Shipped);
        request.setResolveDate(currentDate);
        request.setStatus(WorkRequest.Status.Shipped);

        for (InventoryItem i : request.getInventory().getInventoryItemList()) {
            for (MedicinePackage mp : i.getMedicinePackageList()) {
                Transaction t = mp.getTransactionHistory().newTransaction();
                t.setWorkRequest(receiveShippmentWorkRequest);
            }
        }

        viewWorkQueueJPanel.refreshWorkQueue();
        JOptionPane.showMessageDialog(null, "Selected Order Shipped Successfully");
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_shipOrderJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JLabel drugNameJLabel;
    private javax.swing.JLabel drugNameTitleJLabel;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JTable orderItemJTable;
    private javax.swing.JTable orderJTable;
    private javax.swing.JLabel organizationNameJLabel;
    private javax.swing.JButton shipOrderJButton;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JButton viewDetailsJButton;
    private javax.swing.JLabel wholesalerNameJLabel;
    private javax.swing.JLabel wholesalerNameTitleJLabel;
    // End of variables declaration//GEN-END:variables
}
