/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.Doctor;


import Business.Business;
import Business.Enterprises.Hospital;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.UserAccount;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPanel;



/**
 *
 * @author Mayank
 */
public class HospitalDoctorWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Hospital selectedEnterprise;
    UserAccount userAccount;
    Network selectedNetwork;
    Business business;

    /**
     * Creates new form InventoryManagerJPanel
     */
    public HospitalDoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        
        business = Business.getInstance();
        selectedNetwork = business.getNetworkDirectory().getMyNetwork(userAccount);
        selectedEnterprise = (Hospital)selectedNetwork.getEnterpriseDirectory().getMyEnterprise(userAccount);
        
        enterpriseNameJLabel.setText(" --  " + selectedEnterprise.getEnterpriseName());
        networkNameJLabel.setText(selectedNetwork.getNetworkName());
        
        Organization o = selectedEnterprise.getMyOrganization(userAccount);
        organizationNameJLabel.setText(o.getOrganizationName());

        nameJLabel.setText(userAccount.getEmployee().getPerson().getFirstName() + " " + userAccount.getEmployee().getPerson().getLastName() + " -- ");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        businessNameJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        organizationNameJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nameJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        treatPatientJButton = new javax.swing.JButton();
        viewWorkQueueJButton = new javax.swing.JButton();
        viewWorkRequestsJButton = new javax.swing.JButton();
        reportSuspectDrugJButton = new javax.swing.JButton();

        businessNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        businessNameJLabel.setText("Drug Tracking System");

        enterpriseNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enterpriseNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        enterpriseNameJLabel.setPreferredSize(new java.awt.Dimension(170, 24));

        networkNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        networkNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        networkNameJLabel.setMaximumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setMinimumSize(new java.awt.Dimension(195, 24));
        networkNameJLabel.setPreferredSize(new java.awt.Dimension(195, 24));

        organizationNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        organizationNameJLabel.setMinimumSize(new java.awt.Dimension(170, 24));
        organizationNameJLabel.setPreferredSize(new java.awt.Dimension(190, 24));

        nameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        titleJLabel.setText("My Work Area");

        treatPatientJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        treatPatientJButton.setText("Treat Patient");
        treatPatientJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        treatPatientJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        treatPatientJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        treatPatientJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                treatPatientJButtonMouseReleased(evt);
            }
        });
        treatPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatPatientJButtonActionPerformed(evt);
            }
        });

        viewWorkQueueJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewWorkQueueJButton.setText("View Work Queue");
        viewWorkQueueJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        viewWorkQueueJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        viewWorkQueueJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        viewWorkQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkQueueJButtonActionPerformed(evt);
            }
        });

        viewWorkRequestsJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewWorkRequestsJButton.setText("View Work Requests");
        viewWorkRequestsJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        viewWorkRequestsJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        viewWorkRequestsJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        viewWorkRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkRequestsJButtonActionPerformed(evt);
            }
        });

        reportSuspectDrugJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reportSuspectDrugJButton.setText("Report Suspect Drug");
        reportSuspectDrugJButton.setMaximumSize(new java.awt.Dimension(250, 38));
        reportSuspectDrugJButton.setMinimumSize(new java.awt.Dimension(250, 38));
        reportSuspectDrugJButton.setPreferredSize(new java.awt.Dimension(250, 38));
        reportSuspectDrugJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reportSuspectDrugJButtonMouseReleased(evt);
            }
        });
        reportSuspectDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSuspectDrugJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(businessNameJLabel)
                        .addGap(6, 6, 6)
                        .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(titleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(treatPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(viewWorkQueueJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reportSuspectDrugJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewWorkRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(businessNameJLabel)
                    .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(organizationNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleJLabel))
                .addGap(100, 100, 100)
                .addComponent(treatPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewWorkQueueJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewWorkRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reportSuspectDrugJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void treatPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatPatientJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatPatientJButtonActionPerformed

    private void viewWorkRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkRequestsJButtonActionPerformed
        // TODO add your handling code here:
        ViewWorkRequestsJPanel viewWorkRequestsJPanel = new ViewWorkRequestsJPanel(userProcessContainer, selectedEnterprise, userAccount, selectedNetwork);
        userProcessContainer.add("ViewWorkRequest", viewWorkRequestsJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewWorkRequestsJButtonActionPerformed

    private void viewWorkQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkQueueJButtonActionPerformed
        // TODO add your handling code here:
        ViewWorkQueueJPanel viewWorkQueueJPanel = new ViewWorkQueueJPanel(userProcessContainer, selectedEnterprise, userAccount, selectedNetwork);
        userProcessContainer.add("ViewWorkQueue", viewWorkQueueJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewWorkQueueJButtonActionPerformed

    private void treatPatientJButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatPatientJButtonMouseReleased
        // TODO add your handling code here:
        
        jPopupMenu1.removeAll();
        JMenuItem m1 = new JMenuItem("New Patient");
        JMenuItem m2 = new JMenuItem("Existing Patient");
        
        m1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                AddPatientJPanel addPatientJPanel = new AddPatientJPanel(userProcessContainer, selectedEnterprise, userAccount, selectedNetwork);
                userProcessContainer.add("addPatient", addPatientJPanel);
                CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
                cardLayout.next(userProcessContainer);
            }
        });
        
        m2.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SelectPatientJPanel selectPatientJPanel = new SelectPatientJPanel(userProcessContainer, selectedEnterprise, userAccount, selectedNetwork);
                userProcessContainer.add("selectPatient", selectPatientJPanel);
                CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
                cardLayout.next(userProcessContainer);
            }
        });
        
        
        jPopupMenu1.add(m1);
        jPopupMenu1.add(m2);
        jPopupMenu1.show(treatPatientJButton, treatPatientJButton.getWidth(), treatPatientJButton.getHeight());
    }//GEN-LAST:event_treatPatientJButtonMouseReleased

    private void reportSuspectDrugJButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportSuspectDrugJButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_reportSuspectDrugJButtonMouseReleased

    private void reportSuspectDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSuspectDrugJButtonActionPerformed
        // TODO add your handling code here:
        SelectPatientForReportJPanel selectPatientForReportJPanel = new SelectPatientForReportJPanel(userProcessContainer, selectedEnterprise, userAccount, selectedNetwork);
        userProcessContainer.add("SelectPatientForReport", selectPatientForReportJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);                
    }//GEN-LAST:event_reportSuspectDrugJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel businessNameJLabel;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel organizationNameJLabel;
    private javax.swing.JButton reportSuspectDrugJButton;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JButton treatPatientJButton;
    private javax.swing.JButton viewWorkQueueJButton;
    private javax.swing.JButton viewWorkRequestsJButton;
    // End of variables declaration//GEN-END:variables
}
